name: Earthly Build

on:
  workflow_call:
    inputs:
      BUILT_EARTHLY_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      USE_NEXT:
        required: false
        type: boolean
        default: false

jobs:

  build-earthly:
    name: build (and push) earthly using ${{inputs.BINARY}} and earthly-next=${{inputs.USE_NEXT}}
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    # Needed for the +ci-release target to push to the GitHub Container Registry for later builds
    permissions: write-all
    env:
      FORCE_COLOR: 1
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: earthbuild/actions-setup@main
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Put back the git branch into git (Earthly uses it for tagging)"
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: remove Docker
        run: ${{inputs.SUDO}} apt-get purge docker-engine docker docker.io docker-ce docker-ce-cli ; ${{inputs.SUDO}} rm -rf /usr/bin/docker
        if: inputs.BINARY != 'docker'
      - name: Install Podman (with apt-get)
        run: ${{inputs.SUDO}} apt-get update && ${{inputs.SUDO}} apt-get install -y podman && ${{inputs.SUDO}} rm -f /etc/containers/registries.conf
        if: inputs.binary == 'podman'
      - name: Podman debug info
        run: podman version && podman info && podman info --debug
        if: inputs.BINARY == 'podman'
      - name: Earthly bootstrap
        run: ${{inputs.SUDO}} $(which earthly) bootstrap
      - name: Configure Earthly to use GCR mirror
        run: |-
          ${{inputs.SUDO}} $(which earthly) config global.buildkit_additional_config "'[registry.\"docker.io\"]
          mirrors = [\"mirror.gcr.io\"]'"
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | ${{inputs.SUDO}} ${{inputs.BINARY}} login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Update Buildkit to earthly-next
        if: inputs.USE_NEXT
        run: ${{inputs.SUDO}} $(which earthly) +update-buildkit --BUILDKIT_GIT_SHA=$(cat earthly-next)
      - name: Build latest earthly using released earthly
        run: ${{inputs.SUDO}} $(which earthly) --use-inline-cache +for-linux
      - name: Earthly bootstrap using latest earthly build
        run: ${{inputs.SUDO}} ./build/linux/amd64/earthly bootstrap
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
          echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Build and push +ci-release using latest earthly build
        run: |-
          export TAG_SUFFIX="${{inputs.RUNS_ON}}-${{inputs.BINARY}}"
          if [ "${{inputs.USE_NEXT}}" = "true" ]; then export TAG_SUFFIX="$TAG_SUFFIX-ticktock"; fi
          ${{inputs.SUDO}} ./build/linux/amd64/earthly --ci --push --build-arg TAG_SUFFIX +ci-release
      - name: Buildkit logs (runs on failure)
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthly-buildkitd
        if: ${{ failure() }}
